import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useAuth } from '@/context/auth';
export default function Account(){const auth=useAuth();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const enter=async()=>{setBusy(true);setError('');try{await auth.signIn(email.trim(),password);router.back();}catch(e){setError(e instanceof Error?e.message:'No pudimos iniciar sesión.');}finally{setBusy(false);}};return <ThemedView style={s.screen}><SafeAreaView style={s.safe}><Pressable onPress={()=>router.back()}><ThemedText style={s.back}>‹</ThemedText></Pressable><View style={s.card}><ThemedText style={s.kicker}>ANDERGO LANGUAGE ACADEMY</ThemedText><ThemedText style={s.title}>{auth.session?'Tu cuenta está conectada':'Continúa tu aventura'}</ThemedText>{auth.session?<><ThemedText style={s.body}>{auth.session.email}</ThemedText><Pressable onPress={()=>auth.signOut()} style={s.secondary}><ThemedText style={s.secondaryText}>Cerrar sesión</ThemedText></Pressable></>:<><ThemedText style={s.body}>Usa la misma cuenta de andergo.online para sincronizar tu avance.</ThemedText><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Correo electrónico" style={s.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Contraseña" style={s.input}/>{error?<ThemedText style={s.error}>{error}</ThemedText>:null}<Pressable disabled={busy||!email||!password} onPress={enter} style={s.primary}><ThemedText style={s.primaryText}>{busy?'Conectando…':'Iniciar sesión'}</ThemedText></Pressable></>}</View></SafeAreaView></ThemedView>};
const s=StyleSheet.create({screen:{flex:1},safe:{flex:1,padding:22},back:{fontSize:42,color:'#2563EB'},card:{flex:1,justifyContent:'center',gap:14,maxWidth:460,width:'100%',alignSelf:'center'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#2563EB'},title:{fontSize:32,fontWeight:'900'},body:{fontSize:16,lineHeight:23,color:'#64748B'},input:{height:58,borderRadius:16,paddingHorizontal:16,backgroundColor:'#FFF',borderWidth:1,borderColor:'#CBD5E1',fontSize:16},primary:{height:58,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#2563EB'},primaryText:{fontWeight:'900',fontSize:16,color:'#FFF'},secondary:{height:54,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#EAF2FF'},secondaryText:{fontWeight:'900',color:'#1D4ED8'},error:{color:'#BE123C',fontWeight:'700'}});
