// Expo regenerates typed routes during the native build; this screen adds /account.
// @ts-nocheck
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useGame } from '@/context/game';
import { useAuth } from '@/context/auth';

const WEEK=['L','M','M','J','V','S','D'];

export default function ProgressScreen(){
 const game=useGame(); const auth=useAuth(); const leagueProgress=Math.min(100,(game.xp%500)/5);
 const badges=[
  {icon:'🌟',title:'Primer paso',meta:'Completa tu primera lección',earned:game.lessons>=1},
  {icon:'🔥',title:'En llamas',meta:'Alcanza una racha de 3 días',earned:game.streak>=3},
  {icon:'🎯',title:'Buena puntería',meta:'Obtén 100% en una lección',earned:game.perfectLessons>=1},
  {icon:'⚡',title:'Centurión',meta:'Consigue 100 XP',earned:game.xp>=100},
  {icon:'🗺️',title:'Aventurero',meta:'Completa 5 lecciones',earned:game.lessons>=5},
  {icon:'🏆',title:'Maestro',meta:'Completa 10 lecciones',earned:game.lessons>=10},
 ]; const earned=badges.filter(b=>b.earned).length;
 return <ThemedView style={styles.screen}><SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.nav}><Pressable accessibilityLabel="Volver al inicio" onPress={()=>router.replace('/')} style={styles.back}><ThemedText style={styles.backText}>‹</ThemedText></Pressable><View style={styles.navCopy}><ThemedText style={styles.eyebrow}>TU PERFIL DE AVENTURA</ThemedText><ThemedText style={styles.title}>Explorador nivel {Math.floor(game.xp/200)+1}</ThemedText></View></View><ThemedText style={styles.subtitle}>Cada práctica fortalece tu dominio del idioma.</ThemedText><Pressable onPress={()=>router.push('/account')} style={{minHeight:56,paddingHorizontal:16,borderRadius:18,backgroundColor:'#EAF2FF',flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><ThemedText style={{fontSize:13,fontWeight:'900',color:'#1D4ED8'}}>{auth.session?`Cuenta conectada: ${auth.session.email}`:'Conecta tu cuenta de ANDERGO'}</ThemedText><ThemedText style={{fontSize:18,fontWeight:'900',color:'#1D4ED8'}}>›</ThemedText></Pressable>
  <View style={styles.stats}><Stat color={styles.blue} icon="⚡" value={game.xp} label="XP TOTAL"/><Stat color={styles.orange} icon="🔥" value={game.streak} label="RACHA"/><Stat color={styles.green} icon="✓" value={game.lessons} label="LECCIONES"/></View>
  <View style={styles.card}><View style={styles.cardHead}><View><ThemedText style={styles.cardTitle}>Racha semanal</ThemedText><ThemedText style={styles.cardMeta}>{game.streak} días aprendiendo</ThemedText></View><ThemedText style={styles.bigIcon}>🔥</ThemedText></View><View style={styles.week}>{WEEK.map((day,i)=><View key={`${day}-${i}`} style={styles.day}><View style={[styles.dayCircle,i<Math.min(game.streak,7)&&styles.dayDone]}><ThemedText style={i<Math.min(game.streak,7)&&styles.dayDoneText}>{i<Math.min(game.streak,7)?'✓':'·'}</ThemedText></View><ThemedText style={styles.dayLabel}>{day}</ThemedText></View>)}</View></View>
  <View style={styles.card}><View style={styles.cardHead}><View><ThemedText style={styles.cardTitle}>Liga Zafiro</ThemedText><ThemedText style={styles.cardMeta}>Tu próxima meta semanal</ThemedText></View><ThemedText style={styles.bigIcon}>💎</ThemedText></View><View style={styles.track}><View style={[styles.fill,{width:`${leagueProgress}%`}]} /></View><View style={styles.trackLabels}><ThemedText style={styles.trackStrong}>{game.xp%500} XP</ThemedText><ThemedText style={styles.cardMeta}>500 XP</ThemedText></View><ThemedText style={styles.best}>Mejor precisión: {game.bestScore}%</ThemedText></View>
  <View style={styles.sectionHead}><ThemedText style={styles.sectionTitle}>Insignias</ThemedText><ThemedText style={styles.sectionCount}>{earned} / {badges.length}</ThemedText></View><View style={styles.badges}>{badges.map(b=><View key={b.title} style={[styles.badge,!b.earned&&styles.locked]}><ThemedText style={styles.badgeIcon}>{b.earned?b.icon:'🔒'}</ThemedText><ThemedText style={styles.badgeTitle}>{b.title}</ThemedText><ThemedText style={styles.badgeMeta}>{b.meta}</ThemedText></View>)}</View>
  {game.hearts<5?<Pressable onPress={game.refillHearts} style={[styles.shop,game.coins<20&&styles.locked]} disabled={game.coins<20}><View><ThemedText style={styles.shopTitle}>Recuperar 5 vidas</ThemedText><ThemedText style={styles.shopMeta}>{game.coins>=20?'Usa las monedas ganadas jugando':'Necesitas 20 monedas'}</ThemedText></View><ThemedText style={styles.shopPrice}>🪙 20</ThemedText></Pressable>:<View style={styles.full}><ThemedText style={styles.fullText}>❤️ Tus vidas están completas</ThemedText></View>}
  <Pressable onPress={()=>router.replace('/')} style={styles.home}><ThemedText style={styles.homeText}>Volver a jugar</ThemedText></Pressable>
 </ScrollView></SafeAreaView></ThemedView>;
}
function Stat({color,icon,value,label}:{color:object;icon:string;value:number;label:string}){return <View style={[styles.stat,color]}><ThemedText style={styles.statIcon}>{icon}</ThemedText><ThemedText style={styles.statValue}>{value}</ThemedText><ThemedText style={styles.statLabel}>{label}</ThemedText></View>;}
const styles=StyleSheet.create({screen:{flex:1},safe:{flex:1},content:{padding:20,paddingBottom:70,gap:20,width:'100%',maxWidth:720,alignSelf:'center'},nav:{flexDirection:'row',alignItems:'center',gap:12},back:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},backText:{fontSize:32,lineHeight:35,color:'#2563EB'},navCopy:{flex:1},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#2563EB',marginBottom:5},title:{fontSize:28,lineHeight:34,fontWeight:'900'},subtitle:{fontSize:14,color:'#64748B'},stats:{flexDirection:'row',gap:9},stat:{flex:1,minHeight:120,padding:13,borderRadius:22,justifyContent:'center'},blue:{backgroundColor:'#EAF2FF'},orange:{backgroundColor:'#FFF3E8'},green:{backgroundColor:'#EAFBF1'},statIcon:{fontSize:21},statValue:{fontSize:24,fontWeight:'900'},statLabel:{fontSize:9,fontWeight:'900',color:'#64748B'},card:{padding:18,borderRadius:25,gap:18,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},cardHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cardTitle:{fontSize:19,fontWeight:'900'},cardMeta:{fontSize:11,color:'#64748B'},bigIcon:{fontSize:29},week:{flexDirection:'row',justifyContent:'space-between'},day:{alignItems:'center',gap:5},dayCircle:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#CBD5E1'},dayDone:{backgroundColor:'#2563EB',borderColor:'#2563EB'},dayDoneText:{color:'#FFF',fontWeight:'900'},dayLabel:{fontSize:10,color:'#64748B'},track:{height:11,borderRadius:6,backgroundColor:'#E2E8F0',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#39D5F6'},trackLabels:{flexDirection:'row',justifyContent:'space-between'},trackStrong:{fontSize:12,fontWeight:'900'},best:{fontSize:12,fontWeight:'800',color:'#2563EB'},sectionHead:{flexDirection:'row',justifyContent:'space-between'},sectionTitle:{fontSize:21,fontWeight:'900'},sectionCount:{fontSize:13,fontWeight:'900',color:'#2563EB'},badges:{flexDirection:'row',flexWrap:'wrap',gap:10},badge:{width:'48%',minHeight:140,padding:14,borderRadius:22,justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},locked:{opacity:.43},badgeIcon:{fontSize:29,marginBottom:7},badgeTitle:{fontSize:14,fontWeight:'900'},badgeMeta:{fontSize:10,lineHeight:14,color:'#64748B'},shop:{minHeight:72,padding:16,borderRadius:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#173F91'},shopTitle:{fontSize:15,fontWeight:'900',color:'#FFF'},shopMeta:{fontSize:10,color:'#BFDBFE'},shopPrice:{fontSize:15,fontWeight:'900',color:'#FFF'},full:{minHeight:60,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#ECFDF5'},fullText:{fontSize:14,fontWeight:'900',color:'#047857'},home:{minHeight:58,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:'#2563EB'},homeText:{fontSize:16,fontWeight:'900',color:'#FFF'}});
