import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { useAuth } from '@/context/auth';
import { TargetLanguage, useGame } from '@/context/game';

const LANGUAGES: { id: TargetLanguage; label: string; flag: string }[] = [
  { id: 'english', label: 'Inglés', flag: '🇺🇸' }, { id: 'french', label: 'Francés', flag: '🇫🇷' },
  { id: 'spanish', label: 'Español', flag: '🇪🇸' }, { id: 'italian', label: 'Italiano', flag: '🇮🇹' },
  { id: 'portuguese', label: 'Portugués', flag: '🇧🇷' }, { id: 'german', label: 'Alemán', flag: '🇩🇪' },
];
const MODES = [
  { mode: 'speed', icon: '⚡', title: 'Relámpago', copy: 'Cinco respuestas, sin presión.' },
  { mode: 'match', icon: '🧩', title: 'Parejas', copy: 'Une frases y significados.' },
  { mode: 'order', icon: '🔤', title: 'Ordena', copy: 'Arma una frase a tu ritmo.' },
  { mode: 'listen', icon: '🎧', title: 'Escucha', copy: 'Entrena tu oído jugando.' },
];

export default function HomeScreen() {
  const auth = useAuth(); const game = useGame();
  const current = LANGUAGES.find((language) => language.id === game.targetLanguage) ?? LANGUAGES[0];
  const firstName = auth.session?.displayName?.split(' ')[0];
  const play = (mode = 'speed') => router.push(`/game?mode=${mode}&language=${game.targetLanguage}` as never);
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.topbar}><View><ThemedText style={s.eyebrow}>ANDERGO · APP MÓVIL</ThemedText><ThemedText style={s.greeting}>{firstName ? `¡Hola, ${firstName}!` : 'Aprende con tu ruta'}</ThemedText></View><Pressable onPress={() => router.push('/account' as never)} style={s.profile}><ThemedText style={s.profileText}>{firstName?.slice(0, 1).toUpperCase() ?? '☺'}</ThemedText></Pressable></View>
    {!auth.session ? <Pressable onPress={() => router.push('/account' as never)} style={s.profilePrompt}><View style={s.promptIcon}><ThemedText style={s.promptIconText}>✦</ThemedText></View><View style={s.promptCopy}><ThemedText style={s.promptTitle}>Crea tu perfil gratuito</ThemedText><ThemedText style={s.promptText}>Guarda puntos, premios y tu racha.</ThemedText></View><ThemedText style={s.arrow}>›</ThemedText></Pressable> : null}
    <View style={s.stats}><Stat value={String(game.xp)} label="XP" accent="#2563EB" /><Stat value={String(game.coins)} label="MONEDAS" accent="#D97706" /><Stat value={`${game.streak} 🔥`} label="RACHA" accent="#E11D48" /><Stat value={`${game.hearts}/5`} label="VIDAS" accent="#DB2777" /></View>
    <View style={s.hero}><View style={s.glowOne} /><View style={s.glowTwo} /><ThemedText style={s.heroTag}>TU CURRÍCULO · {current.flag} {current.label.toUpperCase()}</ThemedText><ThemedText style={s.heroTitle}>Tu ruta ANDERGO,{ '\n' }adaptada a móvil.</ThemedText><ThemedText style={s.heroCopy}>Abre las mismas lecciones, audios, lecturas y recursos que existen en la plataforma.</ThemedText><Pressable onPress={() => router.push('/library' as never)} style={s.playButton}><ThemedText style={s.playButtonText}>Abrir mi biblioteca  →</ThemedText></Pressable></View>
    <View style={s.sectionHead}><ThemedText style={s.sectionTitle}>Elige un idioma</ThemedText><ThemedText style={s.sectionHint}>Cámbialo cuando quieras</ThemedText></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.languages}>{LANGUAGES.map((language) => <Pressable key={language.id} onPress={() => game.setTargetLanguage(language.id)} style={[s.language, game.targetLanguage === language.id && s.languageActive]}><ThemedText style={s.flag}>{language.flag}</ThemedText><ThemedText style={[s.languageText, game.targetLanguage === language.id && s.languageTextActive]}>{language.label}</ThemedText></Pressable>)}</ScrollView>
    <View style={s.sectionHead}><ThemedText style={s.sectionTitle}>Práctica rápida</ThemedText><ThemedText style={s.sectionHint}>Complementa tu lección</ThemedText></View>
    <View style={s.modeGrid}>{MODES.map((item) => <Pressable key={item.mode} onPress={() => play(item.mode)} style={s.mode}><View style={s.modeIcon}><ThemedText style={s.modeEmoji}>{item.icon}</ThemedText></View><ThemedText style={s.modeTitle}>{item.title}</ThemedText><ThemedText style={s.modeCopy}>{item.copy}</ThemedText></Pressable>)}</View>
    <Pressable onPress={() => router.push('/visual-vocabulary' as never)} style={s.visualCard}><View style={s.visualIcon}><ThemedText style={s.visualEmoji}>🖼️</ThemedText></View><View style={s.visualCopy}><ThemedText style={s.visualTitle}>Vocabulario visual</ThemedText><ThemedText style={s.visualText}>Juega con las infografías reales de ANDERGO.</ThemedText></View><ThemedText style={s.visualArrow}>→</ThemedText></Pressable>
    <Pressable onPress={() => router.push('/translator' as never)} style={s.translatorCard}><View style={s.translatorIcon}><ThemedText style={s.translatorEmoji}>文</ThemedText></View><View style={s.translatorCopy}><ThemedText style={s.translatorTitle}>Traductor ANDERGO</ThemedText><ThemedText style={s.translatorText}>Traduce, escucha y convierte frases en práctica.</ThemedText></View><ThemedText style={s.translatorArrow}>→</ThemedText></Pressable>
    <Pressable onPress={() => router.push('/library' as never)} style={s.libraryCard}><View style={s.libraryIcon}><ThemedText style={s.libraryEmoji}>📚</ThemedText></View><View style={s.libraryCopy}><ThemedText style={s.libraryTitle}>Biblioteca ANDERGO</ThemedText><ThemedText style={s.libraryText}>Listenings, readings, verbos y vocabulario del proyecto.</ThemedText></View><ThemedText style={s.libraryArrow}>→</ThemedText></Pressable>
    <Pressable onPress={() => router.push('/tutor' as never)} style={s.tutorCard}><View style={s.tutorAvatar}><ThemedText style={s.tutorEmoji}>💬</ThemedText></View><View style={s.tutorCopy}><ThemedText style={s.tutorTitle}>Habla con tu tutor</ThemedText><ThemedText style={s.tutorText}>Practica por texto o voz en {current.label.toLowerCase()}.</ThemedText></View><ThemedText style={s.tutorArrow}>→</ThemedText></Pressable>
    <View style={s.bottomNav}><Nav active icon="⌂" label="Inicio" onPress={() => undefined} /><Nav icon="▤" label="Biblioteca" onPress={() => router.push('/library' as never)} /><Nav icon="◌" label="Tutor" onPress={() => router.push('/tutor' as never)} /><Nav icon="☺" label="Perfil" onPress={() => router.push('/account' as never)} /></View>
  </ScrollView></SafeAreaView>;
}
function Stat({ value, label, accent }: { value: string; label: string; accent: string }) { return <View style={s.stat}><ThemedText style={[s.statValue, { color: accent }]}>{value}</ThemedText><ThemedText style={s.statLabel}>{label}</ThemedText></View>; }
function Nav({ icon, label, active, onPress }: { icon: string; label: string; active?: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={s.navItem}><ThemedText style={[s.navIcon, active && s.navActive]}>{icon}</ThemedText><ThemedText style={[s.navLabel, active && s.navLabelActive]}>{label}</ThemedText></Pressable>; }
const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:'#F6F8FD'},screen:{flex:1},content:{padding:20,paddingBottom:26,gap:18},topbar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:'#2563EB',fontSize:11,fontWeight:'900',letterSpacing:1.5},greeting:{color:'#172554',fontSize:26,fontWeight:'900',marginTop:3},profile:{height:46,width:46,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:'#172554',borderWidth:3,borderColor:'#BFDBFE'},profileText:{color:'#FFF',fontSize:20,fontWeight:'900'},
  profilePrompt:{flexDirection:'row',alignItems:'center',padding:13,gap:11,borderRadius:18,backgroundColor:'#E8F0FF',borderWidth:1,borderColor:'#BFDBFE'},promptIcon:{height:36,width:36,borderRadius:12,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},promptIconText:{color:'#FFF',fontWeight:'900'},promptCopy:{flex:1},promptTitle:{color:'#173F91',fontWeight:'900',fontSize:14},promptText:{color:'#52647F',fontSize:12,marginTop:2},arrow:{color:'#2563EB',fontSize:28},
  stats:{flexDirection:'row',borderRadius:18,backgroundColor:'#FFF',paddingVertical:10,shadowColor:'#172554',shadowOpacity:.06,shadowRadius:14,elevation:2},stat:{flex:1,alignItems:'center',gap:2},statValue:{fontSize:15,fontWeight:'900'},statLabel:{fontSize:8,fontWeight:'900',letterSpacing:.5,color:'#7C8AA3'},
  hero:{overflow:'hidden',borderRadius:27,padding:24,backgroundColor:'#173F91',minHeight:255},glowOne:{position:'absolute',height:190,width:190,borderRadius:100,backgroundColor:'#0EA5E9',opacity:.48,right:-72,top:-54},glowTwo:{position:'absolute',height:120,width:120,borderRadius:80,backgroundColor:'#FBBF24',opacity:.23,right:34,bottom:-56},heroTag:{color:'#BFDBFE',fontSize:10,fontWeight:'900',letterSpacing:.55},heroTitle:{color:'#FFF',fontWeight:'900',fontSize:29,lineHeight:34,marginTop:13},heroCopy:{color:'#DBEAFE',fontSize:14,lineHeight:19,marginTop:9,maxWidth:'77%'},playButton:{alignSelf:'flex-start',marginTop:20,borderRadius:15,paddingHorizontal:18,paddingVertical:13,backgroundColor:'#FFF'},playButtonText:{color:'#1D4ED8',fontSize:14,fontWeight:'900'},
  sectionHead:{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between',marginTop:2},sectionTitle:{color:'#172554',fontSize:19,fontWeight:'900'},sectionHint:{color:'#8190A7',fontSize:10,fontWeight:'700'},languages:{gap:9,paddingRight:18},language:{minWidth:77,paddingVertical:11,paddingHorizontal:9,alignItems:'center',gap:5,borderRadius:17,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E6EAF2'},languageActive:{backgroundColor:'#E8F0FF',borderColor:'#2563EB'},flag:{fontSize:21},languageText:{color:'#64748B',fontSize:10,fontWeight:'800'},languageTextActive:{color:'#1D4ED8'},
  modeGrid:{flexDirection:'row',flexWrap:'wrap',gap:11},mode:{width:'48%',flexGrow:1,minHeight:137,padding:14,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E7EBF2'},modeIcon:{height:38,width:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#E8F0FF'},modeEmoji:{fontSize:20},modeTitle:{color:'#172554',fontSize:15,fontWeight:'900',marginTop:12},modeCopy:{color:'#71809A',fontSize:11,lineHeight:15,marginTop:3},
  visualCard:{flexDirection:'row',alignItems:'center',padding:15,gap:12,borderRadius:20,backgroundColor:'#F0FDF4',borderWidth:1,borderColor:'#BBF7D0'},visualIcon:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#DCFCE7'},visualEmoji:{fontSize:22},visualCopy:{flex:1},visualTitle:{color:'#166534',fontSize:15,fontWeight:'900'},visualText:{color:'#4A7A5B',fontSize:11,lineHeight:15,marginTop:3},visualArrow:{color:'#16A34A',fontSize:22,fontWeight:'900'},translatorCard:{flexDirection:'row',alignItems:'center',padding:15,gap:12,borderRadius:20,backgroundColor:'#F5F3FF',borderWidth:1,borderColor:'#DDD6FE'},translatorIcon:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#EDE9FE'},translatorEmoji:{fontSize:22,fontWeight:'900',color:'#6D28D9'},translatorCopy:{flex:1},translatorTitle:{color:'#5B21B6',fontSize:15,fontWeight:'900'},translatorText:{color:'#7756A5',fontSize:11,lineHeight:15,marginTop:3},translatorArrow:{color:'#7C3AED',fontSize:22,fontWeight:'900'},libraryCard:{flexDirection:'row',alignItems:'center',padding:15,gap:12,borderRadius:20,backgroundColor:'#EEF8FF',borderWidth:1,borderColor:'#BCE5FF'},libraryIcon:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#CBEFFF'},libraryEmoji:{fontSize:22},libraryCopy:{flex:1},libraryTitle:{color:'#0C4A6E',fontSize:15,fontWeight:'900'},libraryText:{color:'#39718C',fontSize:11,lineHeight:15,marginTop:3},libraryArrow:{color:'#0284C7',fontSize:22,fontWeight:'900'},tutorCard:{flexDirection:'row',alignItems:'center',padding:15,gap:12,borderRadius:20,backgroundColor:'#FFF5E7',borderWidth:1,borderColor:'#FDE5BF'},tutorAvatar:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#FFDD9C'},tutorEmoji:{fontSize:22},tutorCopy:{flex:1},tutorTitle:{color:'#713F12',fontSize:15,fontWeight:'900'},tutorText:{color:'#9A6B2B',fontSize:11,lineHeight:15,marginTop:3},tutorArrow:{color:'#B45309',fontSize:22,fontWeight:'900'},bottomNav:{flexDirection:'row',justifyContent:'space-around',paddingTop:10,borderTopWidth:1,borderColor:'#E7EBF2'},navItem:{alignItems:'center',minWidth:47,gap:3},navIcon:{fontSize:19,color:'#94A3B8'},navActive:{color:'#2563EB'},navLabel:{color:'#94A3B8',fontSize:9,fontWeight:'800'},navLabelActive:{color:'#2563EB'},
});
