import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { useAuth } from '@/context/auth';
import { TargetLanguage, useGame } from '@/context/game';
import { CourseLanguage, CurriculumLesson, loadCurriculum } from '@/services/curriculum';

const TABS: { id: CurriculumLesson['skill'] | 'all'; label: string; icon: string }[] = [
  { id: 'all', label: 'Todo', icon: '✦' }, { id: 'listening', label: 'Audio', icon: '🎧' }, { id: 'reading', label: 'Lectura', icon: '📖' }, { id: 'vocabulary', label: 'Palabras', icon: '🧩' }, { id: 'grammar', label: 'Gramática', icon: '⚡' }, { id: 'speaking', label: 'Hablar', icon: '🗣️' }, { id: 'writing', label: 'Escribir', icon: '✍️' },
];
const LABEL: Partial<Record<CurriculumLesson['skill'], string>> = { listening: 'Listening', reading: 'Reading', vocabulary: 'Vocabulario', grammar: 'Gramática y verbos', writing: 'Expresión escrita', speaking: 'Expresión oral' };
const LEVELS: Record<TargetLanguage, string[]> = { english: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'], french: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'], spanish: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'], italian: ['A1', 'A2', 'B1'], portuguese: ['A1', 'A2', 'B1'], german: ['A1', 'A2', 'B1'] };

export default function LibraryScreen() {
  const game = useGame(); const auth = useAuth(); const levels = LEVELS[game.targetLanguage];
  const [tab, setTab] = useState<CurriculumLesson['skill'] | 'all'>('all'); const [level, setLevel] = useState('A1'); const [lessons, setLessons] = useState<CurriculumLesson[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!levels.includes(level)) setLevel('A1'); }, [game.targetLanguage, level, levels]);
  useEffect(() => { let alive = true; setLoading(true); loadCurriculum(game.targetLanguage as CourseLanguage, level, auth.session?.access_token).then((items) => { if (alive) setLessons(items); }).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [game.targetLanguage, level, auth.session?.access_token]);
  const visible = useMemo(() => tab === 'all' ? lessons : lessons.filter((lesson) => lesson.skill === tab), [lessons, tab]);
  const open = (lesson: CurriculumLesson) => { if (lesson.locked || lesson.accessTier === 'premium') { router.push('/account' as never); return; } router.push(`/activity?language=${game.targetLanguage}&level=${level}&slug=${encodeURIComponent(lesson.slug)}&lessonId=${lesson.id}&skill=${lesson.skill}` as never); };
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.header}><Pressable accessibilityLabel="Volver" onPress={() => router.back()} style={s.back}><ThemedText style={s.backText}>‹</ThemedText></Pressable><View style={s.headerCopy}><ThemedText style={s.kicker}>CONTENIDO REAL DE ANDERGO</ThemedText><ThemedText style={s.title}>Mi biblioteca</ThemedText></View></View>
    <ThemedText style={s.intro}>Abre la lección original: lectura, audio oficial, vocabulario y práctica relacionada.</ThemedText>
    <ThemedText style={s.selectorLabel}>Nivel</ThemedText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.levels}>{levels.map((item) => <Pressable key={item} onPress={() => setLevel(item)} style={[s.level, item === level && s.levelActive]}><ThemedText style={[s.levelText, item === level && s.levelTextActive]}>{item}</ThemedText></Pressable>)}</ScrollView>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{TABS.map((item) => <Pressable key={item.id} onPress={() => setTab(item.id)} style={[s.tab, tab === item.id && s.tabActive]}><ThemedText style={[s.tabText, tab === item.id && s.tabTextActive]}>{item.icon} {item.label}</ThemedText></Pressable>)}</ScrollView>
    {loading ? <View style={s.center}><ActivityIndicator color="#2563EB" size="large" /><ThemedText style={s.muted}>Cargando el currículo de ANDERGO…</ThemedText></View> : visible.length ? <View style={s.cards}>{visible.map((lesson) => { const premium = lesson.locked || lesson.accessTier === 'premium'; return <Pressable key={lesson.id} onPress={() => open(lesson)} style={[s.card, premium && s.cardLocked]}><View style={s.cardIcon}><ThemedText style={s.cardEmoji}>{premium ? '🔒' : TABS.find((item) => item.id === lesson.skill)?.icon ?? '✦'}</ThemedText></View><View style={s.cardCopy}><ThemedText style={s.cardType}>{premium ? 'PREMIUM · ' : ''}{LABEL[lesson.skill] ?? 'Lección'}</ThemedText><ThemedText style={s.cardTitle}>{lesson.title}</ThemedText><ThemedText numberOfLines={2} style={s.cardDesc}>{lesson.description || (premium ? 'Disponible con ANDERGO Premium.' : 'Abre la actividad en formato móvil.')}</ThemedText><ThemedText style={s.cardMeta}>{premium ? 'Ver acceso Premium' : `${lesson.estimated_minutes ?? 5} min · +${lesson.xpReward ?? 20} XP`}</ThemedText></View><ThemedText style={s.go}>›</ThemedText></Pressable>; })}</View> : <View style={s.empty}><ThemedText style={s.emptyEmoji}>📚</ThemedText><ThemedText style={s.emptyTitle}>No hay actividades publicadas aquí todavía</ThemedText><ThemedText style={s.muted}>Prueba con otra destreza o nivel.</ThemedText></View>}
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1,backgroundColor:'#F6F8FD'},content:{padding:20,paddingBottom:42,gap:15},header:{flexDirection:'row',alignItems:'center',gap:12},headerCopy:{flex:1},back:{height:42,width:42,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF'},backText:{fontSize:31,lineHeight:34,color:'#2563EB'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#2563EB'},title:{fontSize:25,fontWeight:'900',color:'#172554'},intro:{fontSize:14,lineHeight:20,color:'#64748B'},selectorLabel:{fontSize:11,fontWeight:'900',letterSpacing:.7,color:'#64748B',marginBottom:-7},levels:{gap:8,paddingRight:12},level:{minWidth:49,borderRadius:14,paddingVertical:9,paddingHorizontal:12,alignItems:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#DCE6F7'},levelActive:{backgroundColor:'#172554',borderColor:'#172554'},levelText:{fontSize:12,fontWeight:'900',color:'#475569'},levelTextActive:{color:'#FFF'},tabs:{gap:8,paddingRight:12},tab:{borderRadius:16,paddingHorizontal:13,paddingVertical:10,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},tabActive:{backgroundColor:'#E8F0FF',borderColor:'#93C5FD'},tabText:{fontSize:12,fontWeight:'900',color:'#475569'},tabTextActive:{color:'#1D4ED8'},cards:{gap:11},card:{flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:21,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},cardLocked:{backgroundColor:'#FAFAFC'},cardIcon:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#E8F0FF'},cardEmoji:{fontSize:21},cardCopy:{flex:1},cardType:{fontSize:9,fontWeight:'900',letterSpacing:.7,color:'#2563EB'},cardTitle:{fontSize:15,fontWeight:'900',color:'#172554',marginTop:2},cardDesc:{fontSize:11,lineHeight:15,color:'#64748B',marginTop:3},cardMeta:{fontSize:10,fontWeight:'800',color:'#059669',marginTop:6},go:{fontSize:28,color:'#2563EB'},center:{paddingVertical:80,alignItems:'center',gap:14},empty:{padding:28,borderRadius:25,alignItems:'center',gap:11,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},emptyEmoji:{fontSize:48},emptyTitle:{fontSize:20,fontWeight:'900',color:'#172554',textAlign:'center'},muted:{fontSize:13,lineHeight:19,color:'#64748B',textAlign:'center'} });
