import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { useAuth } from '@/context/auth';
import { TargetLanguage, useGame } from '@/context/game';
import { CurriculumLesson, loadCurriculum } from '@/services/curriculum';

const TABS: { id: CurriculumLesson['skill'] | 'all'; label: string; icon: string }[] = [
  { id: 'all', label: 'Todo', icon: '✦' }, { id: 'listening', label: 'Escuchar', icon: '🎧' },
  { id: 'reading', label: 'Leer', icon: '📖' }, { id: 'vocabulary', label: 'Palabras', icon: '🧩' },
  { id: 'grammar', label: 'Verbos', icon: '⚡' },
];
const MODE: Partial<Record<CurriculumLesson['skill'], string>> = { listening: 'listen', reading: 'story', vocabulary: 'match', grammar: 'review', writing: 'order', speaking: 'speak' };
const LABEL: Partial<Record<CurriculumLesson['skill'], string>> = { listening: 'Listening', reading: 'Reading', vocabulary: 'Vocabulario', grammar: 'Verbos y gramática', writing: 'Construye', speaking: 'Habla' };

export default function LibraryScreen() {
  const game = useGame(); const auth = useAuth(); const [tab, setTab] = useState<CurriculumLesson['skill'] | 'all'>('all'); const [lessons, setLessons] = useState<CurriculumLesson[]>([]); const [loading, setLoading] = useState(true);
  const canLoad = game.targetLanguage !== 'italian';
  useEffect(() => { let alive = true; if (!canLoad) { setLessons([]); setLoading(false); return; } setLoading(true); loadCurriculum(game.targetLanguage as Exclude<TargetLanguage, 'italian'>, 'A1', auth.session?.access_token).then((items) => { if (alive) setLessons(items); }).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [game.targetLanguage, auth.session?.access_token, canLoad]);
  const visible = useMemo(() => tab === 'all' ? lessons.filter((lesson) => ['listening', 'reading', 'vocabulary', 'grammar'].includes(lesson.skill)) : lessons.filter((lesson) => lesson.skill === tab), [lessons, tab]);
  const open = (lesson: CurriculumLesson) => router.push(`/game?mode=${MODE[lesson.skill] ?? 'review'}&language=${game.targetLanguage}&slug=${encodeURIComponent(lesson.slug)}&lessonId=${lesson.id}` as never);
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><ThemedText style={s.backText}>‹</ThemedText></Pressable><View><ThemedText style={s.kicker}>CONTENIDO ANDERGO</ThemedText><ThemedText style={s.title}>Biblioteca de juegos</ThemedText></View></View>
    <ThemedText style={s.intro}>Elige un listening, reading, verbo o grupo de palabras. Tú decides qué practicar.</ThemedText>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{TABS.map((item) => <Pressable key={item.id} onPress={() => setTab(item.id)} style={[s.tab, tab === item.id && s.tabActive]}><ThemedText style={s.tabText}>{item.icon} {item.label}</ThemedText></Pressable>)}</ScrollView>
    {loading ? <View style={s.center}><ActivityIndicator color="#2563EB" size="large" /><ThemedText style={s.muted}>Cargando contenido de ANDERGO…</ThemedText></View> : !canLoad ? <ItalianPlaceholder onPlay={() => router.push('/game?mode=match&language=italian' as never)} /> : visible.length ? <View style={s.cards}>{visible.map((lesson) => <Pressable key={lesson.id} onPress={() => open(lesson)} style={s.card}><View style={s.cardIcon}><ThemedText style={s.cardEmoji}>{TABS.find((item) => item.id === lesson.skill)?.icon ?? '✦'}</ThemedText></View><View style={s.cardCopy}><ThemedText style={s.cardType}>{LABEL[lesson.skill] ?? 'Juego'}</ThemedText><ThemedText style={s.cardTitle}>{lesson.title}</ThemedText><ThemedText numberOfLines={2} style={s.cardDesc}>{lesson.description || 'Toca para jugar con este contenido.'}</ThemedText><ThemedText style={s.cardMeta}>{lesson.estimated_minutes ?? 5} min · +{lesson.xpReward ?? 20} XP</ThemedText></View><ThemedText style={s.go}>›</ThemedText></Pressable>)}</View> : <View style={s.empty}><ThemedText style={s.emptyEmoji}>🎲</ThemedText><ThemedText style={s.emptyTitle}>Pronto habrá más juegos aquí</ThemedText><ThemedText style={s.muted}>Mientras tanto puedes abrir un reto rápido desde Inicio.</ThemedText><Pressable onPress={() => router.replace('/')} style={s.primary}><ThemedText style={s.primaryText}>Ir a jugar</ThemedText></Pressable></View>}
  </ScrollView></SafeAreaView>;
}
function ItalianPlaceholder({ onPlay }: { onPlay: () => void }) { return <View style={s.empty}><ThemedText style={s.emptyEmoji}>🇮🇹</ThemedText><ThemedText style={s.emptyTitle}>Italiano está listo para jugar</ThemedText><ThemedText style={s.muted}>Ya puedes practicar vocabulario y frases. Agregaremos sus listenings y readings del proyecto general a continuación.</ThemedText><Pressable onPress={onPlay} style={s.primary}><ThemedText style={s.primaryText}>Jugar en italiano</ThemedText></Pressable></View>; }
const s = StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FD'},content:{padding:20,paddingBottom:42,gap:18},header:{flexDirection:'row',alignItems:'center',gap:12},back:{height:42,width:42,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF'},backText:{fontSize:31,lineHeight:34,color:'#2563EB'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#2563EB'},title:{fontSize:25,fontWeight:'900',color:'#172554'},intro:{fontSize:14,lineHeight:20,color:'#64748B'},tabs:{gap:8,paddingRight:12},tab:{borderRadius:16,paddingHorizontal:13,paddingVertical:10,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},tabActive:{backgroundColor:'#2563EB',borderColor:'#2563EB'},tabText:{fontSize:12,fontWeight:'900',color:'#475569'},cards:{gap:11},card:{flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:21,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},cardIcon:{height:46,width:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#E8F0FF'},cardEmoji:{fontSize:22},cardCopy:{flex:1},cardType:{fontSize:9,fontWeight:'900',letterSpacing:.7,color:'#2563EB'},cardTitle:{fontSize:15,fontWeight:'900',color:'#172554',marginTop:2},cardDesc:{fontSize:11,lineHeight:15,color:'#64748B',marginTop:3},cardMeta:{fontSize:10,fontWeight:'800',color:'#059669',marginTop:6},go:{fontSize:28,color:'#2563EB'},center:{paddingVertical:80,alignItems:'center',gap:14},empty:{padding:28,borderRadius:25,alignItems:'center',gap:11,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},emptyEmoji:{fontSize:48},emptyTitle:{fontSize:20,fontWeight:'900',color:'#172554',textAlign:'center'},muted:{fontSize:13,lineHeight:19,color:'#64748B',textAlign:'center'},primary:{marginTop:8,minHeight:51,paddingHorizontal:20,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:'#2563EB'},primaryText:{fontSize:14,fontWeight:'900',color:'#FFF'}});
