import { router } from 'expo-router';
import * as Speech from 'expo-speech';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { useAuth } from '@/context/auth';
import { TargetLanguage, useGame } from '@/context/game';

const API = 'https://andergo.online';
const LANGUAGES: { id: TargetLanguage; label: string; flag: string; locale: string }[] = [
  { id: 'english', label: 'Inglés', flag: '🇺🇸', locale: 'en-US' }, { id: 'french', label: 'Francés', flag: '🇫🇷', locale: 'fr-FR' },
  { id: 'spanish', label: 'Español', flag: '🇪🇸', locale: 'es-ES' }, { id: 'italian', label: 'Italiano', flag: '🇮🇹', locale: 'it-IT' },
];
type TranslationResponse = { ok?: boolean; translatedText?: string; message?: string; detectedLanguage?: string };

export default function TranslatorScreen() {
  const auth = useAuth(); const game = useGame(); const [text, setText] = useState(''); const [target, setTarget] = useState<TargetLanguage>(game.targetLanguage === 'spanish' ? 'english' : 'spanish'); const [result, setResult] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const targetInfo = useMemo(() => LANGUAGES.find((language) => language.id === target) ?? LANGUAGES[0], [target]);
  const translate = async () => { const clean = text.trim(); if (!clean || busy) return; setBusy(true); setError(''); try { const response = await fetch(`${API}/api/translate`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(auth.session ? { Authorization: `Bearer ${auth.session.access_token}` } : {}) }, body: JSON.stringify({ text: clean, sourceLanguage: 'auto', targetLanguage: target }) }); const body = await response.json().catch(() => ({})) as TranslationResponse; if (!response.ok || !body.ok || !body.translatedText) throw new Error(body.message || 'No pudimos traducir en este momento.'); setResult(body.translatedText); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No pudimos traducir en este momento.'); } finally { setBusy(false); } };
  const speak = (value: string) => { if (value) Speech.speak(value, { language: targetInfo.locale, rate: .83 }); };
  const swap = () => { if (!result) return; setText(result); setResult(''); setTarget(target === 'spanish' ? game.targetLanguage : 'spanish'); };
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><ThemedText style={s.backText}>‹</ThemedText></Pressable><View><ThemedText style={s.kicker}>HERRAMIENTA ANDERGO</ThemedText><ThemedText style={s.title}>Traductor</ThemedText></View></View><ThemedText style={s.intro}>Traduce una frase y luego úsala para practicar, escuchar o guardarla en tu memoria.</ThemedText>
    <View style={s.languageRow}><View style={s.autoLang}><ThemedText style={s.autoText}>Detectar idioma</ThemedText></View><Pressable onPress={swap} style={s.swap}><ThemedText style={s.swapText}>⇄</ThemedText></Pressable><View style={s.targetWrap}><ThemedText style={s.targetLabel}>TRADUCIR A</ThemedText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.targets}>{LANGUAGES.map((language) => <Pressable key={language.id} onPress={() => { setTarget(language.id); setResult(''); }} style={[s.target, target === language.id && s.targetActive]}><ThemedText style={s.targetText}>{language.flag} {language.label}</ThemedText></Pressable>)}</ScrollView></View></View>
    <View style={s.inputCard}><TextInput value={text} onChangeText={(value) => { setText(value); setError(''); }} placeholder="Escribe aquí una palabra, frase o idea…" multiline textAlignVertical="top" style={s.input} maxLength={480} /><View style={s.inputFoot}><ThemedText style={s.count}>{text.length}/480</ThemedText><Pressable onPress={() => setText('')}><ThemedText style={s.clear}>Limpiar</ThemedText></Pressable></View></View><Pressable disabled={!text.trim() || busy} onPress={translate} style={[s.primary, (!text.trim() || busy) && s.primaryDisabled]}><ThemedText style={s.primaryText}>{busy ? 'Traduciendo…' : 'Traducir'}</ThemedText></Pressable>
    {error ? <View style={s.error}><ThemedText style={s.errorText}>{error}</ThemedText></View> : null}{result ? <View style={s.resultCard}><View style={s.resultHead}><ThemedText style={s.resultLabel}>{targetInfo.flag} {targetInfo.label.toUpperCase()}</ThemedText><Pressable onPress={() => speak(result)} style={s.listen}><ThemedText style={s.listenText}>🔊 Escuchar</ThemedText></Pressable></View><ThemedText selectable style={s.resultText}>{result}</ThemedText><Pressable onPress={() => router.push(`/game?mode=review&language=${target}` as never)} style={s.practice}><ThemedText style={s.practiceText}>Practicar este idioma  →</ThemedText></Pressable></View> : null}
    <View style={s.tip}><ThemedText style={s.tipTitle}>Consejo de ANDERGO</ThemedText><ThemedText style={s.tipText}>Traduce frases completas. Luego escúchalas y repítelas con el Tutor para que se conviertan en práctica real.</ThemedText></View>
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FD'},content:{padding:20,paddingBottom:40,gap:17},header:{flexDirection:'row',alignItems:'center',gap:12},back:{height:42,width:42,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF'},backText:{fontSize:31,lineHeight:34,color:'#2563EB'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#2563EB'},title:{fontSize:26,fontWeight:'900',color:'#172554'},intro:{fontSize:14,lineHeight:20,color:'#64748B'},languageRow:{gap:8},autoLang:{alignSelf:'flex-start',paddingHorizontal:13,paddingVertical:9,borderRadius:14,backgroundColor:'#E8F0FF'},autoText:{fontSize:12,fontWeight:'900',color:'#1D4ED8'},swap:{position:'absolute',right:0,top:0,height:38,width:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},swapText:{fontSize:19,color:'#2563EB'},targetWrap:{gap:7},targetLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#64748B'},targets:{gap:7,paddingRight:8},target:{paddingVertical:9,paddingHorizontal:11,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},targetActive:{backgroundColor:'#173F91',borderColor:'#173F91'},targetText:{fontSize:11,fontWeight:'900',color:'#475569'},inputCard:{minHeight:166,padding:15,borderRadius:22,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D9E0EA'},input:{minHeight:112,fontSize:16,lineHeight:23,color:'#172554'},inputFoot:{flexDirection:'row',justifyContent:'space-between'},count:{fontSize:10,color:'#94A3B8'},clear:{fontSize:11,fontWeight:'900',color:'#2563EB'},primary:{minHeight:56,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#2563EB'},primaryDisabled:{opacity:.42},primaryText:{fontSize:16,fontWeight:'900',color:'#FFF'},error:{padding:14,borderRadius:16,backgroundColor:'#FFF1F2'},errorText:{fontSize:13,fontWeight:'800',color:'#BE123C'},resultCard:{padding:17,borderRadius:22,backgroundColor:'#ECFDF5',borderWidth:1,borderColor:'#A7F3D0',gap:10},resultHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resultLabel:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#047857'},listen:{paddingVertical:7,paddingHorizontal:10,borderRadius:11,backgroundColor:'#D1FAE5'},listenText:{fontSize:11,fontWeight:'900',color:'#047857'},resultText:{fontSize:21,lineHeight:29,fontWeight:'800',color:'#064E3B'},practice:{alignSelf:'flex-start',marginTop:4},practiceText:{fontSize:12,fontWeight:'900',color:'#047857'},tip:{padding:16,borderRadius:20,backgroundColor:'#FFF5E7'},tipTitle:{fontSize:13,fontWeight:'900',color:'#92400E'},tipText:{fontSize:12,lineHeight:18,color:'#A16207',marginTop:4}});
