import { router } from 'expo-router';
import { Image } from 'expo-image';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { useGame } from '@/context/game';
import { shuffle } from '@/utils/game-random';

type VisualLanguage = 'english' | 'french' | 'spanish' | 'italian';
type Word = Record<VisualLanguage, string>;
const TOPICS: { id: string; title: string; image: string; words: Word[] }[] = [
  { id: 'food', title: 'Comida', image: 'https://andergo.online/images/infographics/topics/food.png', words: [
    { spanish: 'manzana', english: 'apple', french: 'pomme', italian: 'mela' }, { spanish: 'pan', english: 'bread', french: 'pain', italian: 'pane' },
    { spanish: 'agua', english: 'water', french: 'eau', italian: 'acqua' }, { spanish: 'queso', english: 'cheese', french: 'fromage', italian: 'formaggio' },
  ] },
  { id: 'family', title: 'Familia', image: 'https://andergo.online/images/infographics/topics/family.png', words: [
    { spanish: 'madre', english: 'mother', french: 'mère', italian: 'madre' }, { spanish: 'padre', english: 'father', french: 'père', italian: 'padre' },
    { spanish: 'hermana', english: 'sister', french: 'sœur', italian: 'sorella' }, { spanish: 'bebé', english: 'baby', french: 'bébé', italian: 'neonato' },
  ] },
  { id: 'classroom', title: 'Aula', image: 'https://andergo.online/images/infographics/topics/classroom.png', words: [
    { spanish: 'libro', english: 'book', french: 'livre', italian: 'libro' }, { spanish: 'silla', english: 'chair', french: 'chaise', italian: 'sedia' },
    { spanish: 'lápiz', english: 'pencil', french: 'crayon', italian: 'matita' }, { spanish: 'mesa', english: 'table', french: 'table', italian: 'tavolo' },
  ] },
  { id: 'weather', title: 'Clima', image: 'https://andergo.online/images/infographics/topics/weather.png', words: [
    { spanish: 'sol', english: 'sun', french: 'soleil', italian: 'sole' }, { spanish: 'lluvia', english: 'rain', french: 'pluie', italian: 'pioggia' },
    { spanish: 'nube', english: 'cloud', french: 'nuage', italian: 'nuvola' }, { spanish: 'viento', english: 'wind', french: 'vent', italian: 'vento' },
  ] },
];
const LANGUAGE_LABEL: Record<VisualLanguage, string> = { english: 'inglés', french: 'francés', spanish: 'español', italian: 'italiano' };

export default function VisualVocabularyScreen() {
  const game = useGame(); const [topicIndex, setTopicIndex] = useState(0); const [round, setRound] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [correct, setCorrect] = useState(0); const [done, setDone] = useState(false); const [choicesSeed, setChoicesSeed] = useState(() => Math.random());
  const topic = TOPICS[topicIndex]; const word = topic.words[round]; const language = game.targetLanguage;
  const visualLanguage = (['english', 'french', 'spanish', 'italian'] as string[]).includes(language) ? language as VisualLanguage : null;
  const options = useMemo(() => shuffle(topic.words.map((item) => item[visualLanguage ?? 'english']), choicesSeed + round), [topic, visualLanguage, round, choicesSeed]);
  const choose = (answer: string) => { if (selected) return; setSelected(answer); if (answer === word[visualLanguage ?? 'english']) setCorrect((value) => value + 1); };
  const next = () => { if (round === topic.words.length - 1) { game.finishLesson(correct + (selected === word[visualLanguage ?? 'english'] ? 1 : 0), topic.words.length); setDone(true); return; } setRound((value) => value + 1); setSelected(null); setChoicesSeed((value) => value + 1); };
  const chooseTopic = (index: number) => { setTopicIndex(index); setRound(0); setSelected(null); setCorrect(0); setDone(false); setChoicesSeed((value) => value + 1); };
  if (!visualLanguage) return <SafeAreaView style={s.safe}><View style={s.result}><ThemedText style={s.trophy}>🖼️</ThemedText><ThemedText style={s.resultTitle}>Vocabulario visual en preparación</ThemedText><ThemedText style={s.resultText}>La Biblioteca ya ofrece contenido real de ANDERGO en este idioma. El álbum visual llegará con equivalencias revisadas.</ThemedText><Pressable onPress={() => router.replace('/library')} style={s.primary}><ThemedText style={s.primaryText}>Abrir biblioteca</ThemedText></Pressable><Pressable onPress={() => router.back()}><ThemedText style={s.home}>Volver</ThemedText></Pressable></View></SafeAreaView>;
  if (done) return <SafeAreaView style={s.safe}><View style={s.result}><ThemedText style={s.trophy}>🖼️</ThemedText><ThemedText style={s.kicker}>ÁLBUM COMPLETADO</ThemedText><ThemedText style={s.resultTitle}>{correct >= 3 ? '¡Muy buena vista!' : '¡Buen intento!'}</ThemedText><ThemedText style={s.resultText}>Ganaste XP y monedas por jugar con la infografía de {topic.title.toLowerCase()}.</ThemedText><Pressable onPress={() => chooseTopic((topicIndex + 1) % TOPICS.length)} style={s.primary}><ThemedText style={s.primaryText}>Abrir otra infografía</ThemedText></Pressable><Pressable onPress={() => router.replace('/')}><ThemedText style={s.home}>Volver al inicio</ThemedText></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.top}><Pressable onPress={() => router.back()} style={s.close}><ThemedText style={s.closeText}>×</ThemedText></Pressable><View style={s.progress}><View style={[s.fill, { width: `${((round + 1) / topic.words.length) * 100}%` }]} /></View><ThemedText style={s.hearts}>❤️ {game.hearts}</ThemedText></View>
    <View><ThemedText style={s.kicker}>VOCABULARIO VISUAL · {topic.title.toUpperCase()}</ThemedText><ThemedText style={s.title}>Mira la imagen y juega.</ThemedText><ThemedText style={s.copy}>¿Cómo se dice <ThemedText style={s.word}>{word.spanish}</ThemedText> en {LANGUAGE_LABEL[visualLanguage]}?</ThemedText></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.topicBar}>{TOPICS.map((item, index) => <Pressable key={item.id} onPress={() => chooseTopic(index)} style={[s.topic, topicIndex === index && s.topicActive]}><ThemedText style={[s.topicText, topicIndex === index && s.topicTextActive]}>{item.title}</ThemedText></Pressable>)}</ScrollView>
    <View style={s.imageWrap}><Image source={{ uri: topic.image }} style={s.image} contentFit="cover" transition={250} /><View style={s.imageLabel}><ThemedText style={s.imageLabelText}>Infografía ANDERGO</ThemedText></View></View>
    <View style={s.answers}>{options.map((option) => <Pressable key={option} disabled={!!selected} onPress={() => choose(option)} style={[s.answer, selected === option && option === word[visualLanguage] && s.answerGood, selected === option && option !== word[visualLanguage] && s.answerBad]}><ThemedText style={s.answerText}>{option}</ThemedText>{selected && option === word[visualLanguage] ? <ThemedText style={s.check}>✓</ThemedText> : null}</Pressable>)}</View>
    {selected ? <View style={[s.feedback, selected === word[visualLanguage] ? s.good : s.bad]}><View style={s.feedbackCopy}><ThemedText style={s.feedbackTitle}>{selected === word[visualLanguage] ? '¡Correcto!' : 'Casi…'}</ThemedText><ThemedText style={s.feedbackText}>{word.spanish} = {word[visualLanguage]}</ThemedText></View><Pressable onPress={next} style={s.next}><ThemedText style={s.nextText}>{round === topic.words.length - 1 ? 'Resultado' : 'Siguiente'}</ThemedText></Pressable></View> : null}
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FD'},content:{padding:20,paddingBottom:30,gap:18},top:{height:45,flexDirection:'row',alignItems:'center',gap:12},close:{height:40,width:40,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF'},closeText:{fontSize:27,color:'#64748B'},progress:{flex:1,height:10,borderRadius:8,overflow:'hidden',backgroundColor:'#E2E8F0'},fill:{height:'100%',backgroundColor:'#22C55E'},hearts:{fontSize:13,fontWeight:'900'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#2563EB'},title:{fontSize:27,fontWeight:'900',color:'#172554',marginTop:5},copy:{fontSize:15,color:'#64748B',marginTop:7},word:{fontWeight:'900',color:'#1D4ED8'},topicBar:{gap:8,paddingRight:10},topic:{paddingVertical:9,paddingHorizontal:14,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0'},topicActive:{backgroundColor:'#173F91',borderColor:'#173F91'},topicText:{fontSize:12,fontWeight:'900',color:'#64748B'},topicTextActive:{color:'#FFF'},imageWrap:{height:224,borderRadius:24,overflow:'hidden',backgroundColor:'#E2E8F0'},image:{height:'100%',width:'100%'},imageLabel:{position:'absolute',left:10,bottom:10,paddingVertical:6,paddingHorizontal:10,borderRadius:10,backgroundColor:'rgba(23,63,145,.88)'},imageLabelText:{fontSize:10,fontWeight:'900',color:'#FFF'},answers:{gap:10},answer:{minHeight:56,paddingHorizontal:16,borderWidth:2,borderColor:'#E2E8F0',borderRadius:17,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},answerText:{fontSize:16,fontWeight:'800',color:'#172554'},answerGood:{backgroundColor:'#ECFDF5',borderColor:'#10B981'},answerBad:{backgroundColor:'#FFF1F2',borderColor:'#FB7185'},check:{fontSize:21,color:'#059669',fontWeight:'900'},feedback:{marginHorizontal:-20,padding:15,paddingBottom:26,flexDirection:'row',alignItems:'center',gap:10},good:{backgroundColor:'#D1FAE5'},bad:{backgroundColor:'#FFE4E6'},feedbackCopy:{flex:1},feedbackTitle:{fontSize:15,fontWeight:'900'},feedbackText:{fontSize:12,color:'#475569'},next:{minHeight:47,paddingHorizontal:15,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#173F91'},nextText:{fontSize:13,fontWeight:'900',color:'#FFF'},result:{flex:1,alignItems:'center',justifyContent:'center',padding:30,gap:15},trophy:{fontSize:76},resultTitle:{fontSize:31,fontWeight:'900',color:'#172554',textAlign:'center'},resultText:{fontSize:15,lineHeight:22,color:'#64748B',textAlign:'center'},primary:{minHeight:56,width:'100%',marginTop:10,borderRadius:18,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontSize:15,fontWeight:'900'},home:{fontSize:13,fontWeight:'900',color:'#2563EB'}});
